version: '3'

services:
  nginx:
    image: ecs-hands-on/nginx:latest
    volumes:
      - ./docker/nginx/local/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    expose:
      - 8080
    depends_on:
      - laravel
  laravel:
    image: ecs-hands-on/laravel:latest
    volumes:
      - ./src:/application
    env_file:
      - ./src/.env